// Animation.jsx
import React from 'react';
import styled, { css } from 'styled-components';

// Keyframes imports - add other animations as needed
import {
  BreatheAnimation,
  PulseAnimation,
  SpinAnimation,
  FadeInOutAnimation,
  BounceAnimation,
  ShakeAnimation,
  PopAnimation,
  SlideInAnimation,
  SlideOutAnimation,
  FlipAnimation,
  JellyAnimation,
  WobbleAnimation,
  RubberBandAnimation,
  FadeUpAnimation,
  FadeDownAnimation,
  FadeLeftAnimation,
  FadeRightAnimation,
  GlowAnimation,
  BlinkingAnimation,
  HeartbeatAnimation,
  ZoomInAnimation,
  ZoomOutAnimation,
  StretchAnimation,
  FlashAnimation,
  SlideUpAnimation,
  SlideDownAnimation,
  BounceInAnimation,
  BounceOutAnimation,
  RippleAnimation,
  ShrinkGrowAnimation,
  FloatAnimation,
  SwingingAnimation,
  TwistAnimation,
  GrowShrinkAnimation,
  WaveAnimation,
  BlipAnimation,
  SkewAnimation,
  RollInAnimation,
  RollOutAnimation,
  StretchOutAnimation,
  StretchInAnimation,
  FlickerAnimation,
  BounceLeftAnimation,
  BounceRightAnimation,
  DropAnimation,
  ExpandAnimation,
  ContractAnimation,
  TwinkleAnimation,
  ExpandUpAnimation,
  ExpandDownAnimation,
  RotateXAnimation,
  RotateYAnimation,
  StretchHorizontalAnimation,
  StretchVerticalAnimation,
  FadeDiagonalAnimation,
  ColorShiftAnimation,
  ScaleUpAnimation,
  ScaleDownAnimation,
  PopOutAnimation,
  PopInAnimation,
  SpiralAnimation,
  BlurInAnimation,
  BlurOutAnimation,
  FlipXAnimation,
  FlipYAnimation,
  RotateZAnimation,
  ScaleBounceAnimation,
  SlideDiagonalAnimation,
  FadeRotateAnimation,
  BlinkScaleAnimation,
  BounceTwistAnimation,
  ShimmerAnimation,
  WaveVerticalAnimation,
  SkewXAnimation,
  SkewYAnimation,
  DriftAnimation,
  ScaleFadeAnimation,
  StretchDiagonalAnimation,
  FlashScaleAnimation,
  SwingXAnimation,
  SwingYAnimation,
  PulseOpacityAnimation,
  ScaleRotateAnimation,
  ShiftLeftAnimation,
  ShiftRightAnimation,
  SlideShrinkAnimation,
  ZoomBlinkAnimation,
  PushDownAnimation,
  PushUpAnimation,
  ScaleFlashAnimation,
  SlideUpFadeAnimation,
  SlideDownFadeAnimation,
  ZoomSpinAnimation,
  SwayAnimation,
  PushBackAnimation,
  PulseRotateAnimation,
  ExpandCollapseAnimation,
  PushPullAnimation,
  BounceOpacityAnimation,
  SpinBounceAnimation,
  CrossFadeAnimation,
  PushZoomAnimation,
  ElasticAnimation,
  SlideFadeAnimation,
  GlowPulseAnimation,
  SlideFlipAnimation,
  SlideSkewAnimation,
  CircleExpandAnimation,
  FlipFadeAnimation,
  TiltShiftAnimation,
  SwayRotateAnimation,
  ZigzagAnimation,
  StretchGlowAnimation,
  SwingFadeAnimation,
  GrowShrinkDiagonalAnimation,
  SpiralOutAnimation,
  BounceRotateAnimation,
  FlashTiltAnimation,
  StretchBounceAnimation,
  WaveDiagonalAnimation,
  PopUpAnimation,
  DropShrinkAnimation,
  RotatePulseAnimation,
  ExpandRotateAnimation,
  SwipeAnimation,
  SpinGrowAnimation,
  FlickerZoomAnimation,
  StretchFadeAnimation,
  SwingAnimation,
  SlideUpGrowAnimation,
  SpinSkewAnimation,
  TwirlAnimation,
  PulseDiagonalAnimation,
  ShrinkBounceAnimation,
  BounceSlideAnimation,
  RotateScaleFadeAnimation,
  FlipExpandAnimation,
  GlideInAnimation,
  SpinPulseAnimation,
  FadeSlideAnimation,
  SlideGlowAnimation,
  PopSkewAnimation,
  PulseGrowAnimation,
  StretchShiftAnimation,
  CollapseExpandAnimation,
  // ... add more animations here as needed
} from './Keyframes'; // Import the keyframes from your animations file

// Mapping animation names to keyframes
const animationsMap = {
  Breathe: BreatheAnimation,
  Pulse: PulseAnimation,
  Spin: SpinAnimation,
  FadeInOut: FadeInOutAnimation,
  Bounce: BounceAnimation,
  Shake: ShakeAnimation,
  Pop: PopAnimation,
  SlideIn: SlideInAnimation,
  SlideOut: SlideOutAnimation,
  Flip: FlipAnimation,
  Jelly: JellyAnimation,
  Wobble: WobbleAnimation,
  RubberBand: RubberBandAnimation,
  FadeUp: FadeUpAnimation,
  FadeDown: FadeDownAnimation,
  FadeLeft: FadeLeftAnimation,
  FadeRight: FadeRightAnimation,
  Glow: GlowAnimation,
  Blinking: BlinkingAnimation,
  Heartbeat: HeartbeatAnimation,
  ZoomIn: ZoomInAnimation,
  ZoomOut: ZoomOutAnimation,
  Stretch: StretchAnimation,
  Flash: FlashAnimation,
  SlideUp: SlideUpAnimation,
  SlideDown: SlideDownAnimation,
  BounceIn: BounceInAnimation,
  BounceOut: BounceOutAnimation,
  Ripple: RippleAnimation,
  ShrinkGrow: ShrinkGrowAnimation,
  Float: FloatAnimation,
  Swinging: SwingingAnimation,
  Twist: TwistAnimation,
  GrowShrink: GrowShrinkAnimation,
  Wave: WaveAnimation,
  Blip: BlipAnimation,
  Skew: SkewAnimation,
  RollIn: RollInAnimation,
  RollOut: RollOutAnimation,
  StretchOut: StretchOutAnimation,
  StretchIn: StretchInAnimation,
  Flicker: FlickerAnimation,
  BounceLeft: BounceLeftAnimation,
  BounceRight: BounceRightAnimation,
  Drop: DropAnimation,
  Expand: ExpandAnimation,
  Contract: ContractAnimation,
  Twinkle: TwinkleAnimation,
  ExpandUp: ExpandUpAnimation,
  ExpandDown: ExpandDownAnimation,
  RotateX: RotateXAnimation,
  RotateY: RotateYAnimation,
  StretchHorizontal: StretchHorizontalAnimation,
  StretchVertical: StretchVerticalAnimation,
  FadeDiagonal: FadeDiagonalAnimation,
  ColorShift: ColorShiftAnimation,
  ScaleUp: ScaleUpAnimation,
  ScaleDown: ScaleDownAnimation,
  PopOut: PopOutAnimation,
  PopIn: PopInAnimation,
  Spiral: SpiralAnimation,
  BlurIn: BlurInAnimation,
  BlurOut: BlurOutAnimation,
  FlipX: FlipXAnimation,
  FlipY: FlipYAnimation,
  RotateZ: RotateZAnimation,
  ScaleBounce: ScaleBounceAnimation,
  SlideDiagonal: SlideDiagonalAnimation,
  FadeRotate: FadeRotateAnimation,
  BlinkScale: BlinkScaleAnimation,
  BounceTwist: BounceTwistAnimation,
  Shimmer: ShimmerAnimation,
  WaveVertical: WaveVerticalAnimation,
  SkewX: SkewXAnimation,
  SkewY: SkewYAnimation,
  Drift: DriftAnimation,
  ScaleFade: ScaleFadeAnimation,
  StretchDiagonal: StretchDiagonalAnimation,
  FlashScale: FlashScaleAnimation,
  SwingX: SwingXAnimation,
  SwingY: SwingYAnimation,
  PulseOpacity: PulseOpacityAnimation,
  ScaleRotate: ScaleRotateAnimation,
  ShiftLeft: ShiftLeftAnimation,
  ShiftRight: ShiftRightAnimation,
  SlideShrink: SlideShrinkAnimation,
  ZoomBlink: ZoomBlinkAnimation,
  PushDown: PushDownAnimation,
  PushUp: PushUpAnimation,
  ScaleFlash: ScaleFlashAnimation,
  SlideUpFade: SlideUpFadeAnimation,
  SlideDownFade: SlideDownFadeAnimation,
  ZoomSpin: ZoomSpinAnimation,
  Sway: SwayAnimation,
  PushBack: PushBackAnimation,
  PulseRotate: PulseRotateAnimation,
  ExpandCollapse: ExpandCollapseAnimation,
  PushPull: PushPullAnimation,
  BounceOpacity: BounceOpacityAnimation,
  SpinBounce: SpinBounceAnimation,
  CrossFade: CrossFadeAnimation,
  PushZoom: PushZoomAnimation,
  Elastic: ElasticAnimation,
  SlideFade: SlideFadeAnimation,
  GlowPulse: GlowPulseAnimation,
  SlideFlip: SlideFlipAnimation,
  SlideSkew: SlideSkewAnimation,
  CircleExpand: CircleExpandAnimation,
  FlipFade: FlipFadeAnimation,
  TiltShift: TiltShiftAnimation,
  SwayRotate: SwayRotateAnimation,
  Zigzag: ZigzagAnimation,
  StretchGlow: StretchGlowAnimation,
  SwingFade: SwingFadeAnimation,
  GrowShrinkDiagonal: GrowShrinkDiagonalAnimation,
  SpiralOut: SpiralOutAnimation,
  BounceRotate: BounceRotateAnimation,
  FlashTilt: FlashTiltAnimation,
  StretchBounce: StretchBounceAnimation,
  WaveDiagonal: WaveDiagonalAnimation,
  PopUp: PopUpAnimation,
  DropShrink: DropShrinkAnimation,
  RotatePulse: RotatePulseAnimation,
  ExpandRotate: ExpandRotateAnimation,
  Swipe: SwipeAnimation,
  SpinGrow: SpinGrowAnimation,
  FlickerZoom: FlickerZoomAnimation,
  StretchFade: StretchFadeAnimation,
  Swing: SwingAnimation,
  SlideUpGrow: SlideUpGrowAnimation,
  SpinSkew: SpinSkewAnimation,
  Twirl: TwirlAnimation,
  PulseDiagonal: PulseDiagonalAnimation,
  ShrinkBounce: ShrinkBounceAnimation,
  BounceSlide: BounceSlideAnimation,
  RotateScaleFade: RotateScaleFadeAnimation,
  FlipExpand: FlipExpandAnimation,
  GlideIn: GlideInAnimation,
  SpinPulse: SpinPulseAnimation,
  FadeSlide: FadeSlideAnimation,
  SlideGlow: SlideGlowAnimation,
  PopSkew: PopSkewAnimation,
  PulseGrow: PulseGrowAnimation,
  StretchShift: StretchShiftAnimation,
  CollapseExpand: CollapseExpandAnimation,
  // ... add more mappings here
};

// Styled component for animated wrapper
const AnimatedWrapper = styled.div`
  ${({ animation, duration, delay, iteration, timingFunction }) => css`
    animation: ${animationsMap[animation]} ${duration || '1s'}
      ${timingFunction || 'ease-in-out'} ${delay || '0s'}
      ${iteration || 'infinite'};
  `}
`;

// Main Animation component
const Animation = ({
  animation = 'ripple',
  duration,
  delay,
  iteration,
  timingFunction,
  children,
}) => {
  return (
    <AnimatedWrapper
      animation={animation}
      duration={duration}
      delay={delay}
      iteration={iteration}
      timingFunction={timingFunction}
    >
      {children}
    </AnimatedWrapper>
  );
};

export default Animation;
