// Animation.stories.jsx
import React from 'react';
import Animation from './Animation';

const List = [
  'Breathe',
  'Pulse',
  'Spin',
  'FadeInOut',
  'Bounce',
  'Shake',
  'Pop',
  'SlideIn',
  'SlideOut',
  'Flip',
  'Jelly',
  'Wobble',
  'RubberBand',
  'FadeUp',
  'FadeDown',
  'FadeLeft',
  'FadeRight',
  'Glow',
  'Blinking',
  'Heartbeat',
  'ZoomIn',
  'ZoomOut',
  'Stretch',
  'Flash',
  'SlideUp',
  'SlideDown',
  'BounceIn',
  'BounceOut',
  'Ripple',
  'ShrinkGrow',
  'Float',
  'Swinging',
  'Twist',
  'GrowShrink',
  'Wave',
  'Blip',
  'Skew',
  'RollIn',
  'RollOut',
  'StretchOut',
  'StretchIn',
  'Flicker',
  'BounceLeft',
  'BounceRight',
  'Drop',
  'Expand',
  'Contract',
  'Twinkle',
  'ExpandUp',
  'ExpandDown',
  'RotateX',
  'RotateY',
  'StretchHorizontal',
  'StretchVertical',
  'FadeDiagonal',
  'ColorShift',
  'ScaleUp',
  'ScaleDown',
  'PopOut',
  'PopIn',
  'Spiral',
  'BlurIn',
  'BlurOut',
  'FlipX',
  'FlipY',
  'RotateZ',
  'ScaleBounce',
  'SlideDiagonal',
  'FadeRotate',
  'BlinkScale',
  'BounceTwist',
  'Shimmer',
  'WaveVertical',
  'SkewX',
  'SkewY',
  'Drift',
  'ScaleFade',
  'StretchDiagonal',
  'FlashScale',
  'SwingX',
  'SwingY',
  'PulseOpacity',
  'ScaleRotate',
  'ShiftLeft',
  'ShiftRight',
  'SlideShrink',
  'ZoomBlink',
  'PushDown',
  'PushUp',
  'ScaleFlash',
  'SlideUpFade',
  'SlideDownFade',
  'ZoomSpin',
  'Sway',
  'PushBack',
  'PulseRotate',
  'ExpandCollapse',
  'PushPull',
  'BounceOpacity',
  'SpinBounce',
  'CrossFade',
  'PushZoom',
  'Elastic',
  'SlideFade',
  'GlowPulse',
  'SlideFlip',
  'SlideSkew',
  'CircleExpand',
  'FlipFade',
  'TiltShift',
  'SwayRotate',
  'Zigzag',
  'StretchGlow',
  'SwingFade',
  'GrowShrinkDiagonal',
  'SpiralOut',
  'BounceRotate',
  'FlashTilt',
  'StretchBounce',
  'WaveDiagonal',
  'PopUp',
  'DropShrink',
  'RotatePulse',
  'ExpandRotate',
  'Swipe',
  'SpinGrow',
  'FlickerZoom',
  'StretchFade',
  'SlideUpGrow',
  'Swing',
  'SpinSkew',
  'Twirl',
  'PulseDiagonal',
  'ShrinkBounce',
  'BounceSlide',
  'RotateScaleFade',
  'FlipExpand',
  'GlideIn',
  'SpinPulse',
  'FadeSlide',
  'SlideGlow',
  'PopSkew',
  'PulseGrow',
  'StretchShift',
  'CollapseExpand',
  // Add more animations to the options list as needed
];

// Export default settings for Storybook
export default {
  title: 'Animation/Animation',
  component: Animation,
  argTypes: {
    animation: {
      control: 'select',
      options: List,
    },
    duration: { control: 'text' },
    delay: { control: 'text' },
    iteration: { control: 'text' },
    timingFunction: { control: 'text' },
  },
};

// Template for the Animation component
const Template = (args) => (
  <Animation {...args}>
    <div
      style={{
        width: '100px',
        height: '100px',
        backgroundColor: 'black',
        borderRadius: '6px',
      }}
    ></div>
  </Animation>
);

export const Elastic = Template.bind({});
Elastic.args = {
  animation: 'Elastic',
  duration: '2s',
  delay: '0s',
  iteration: 'infinite',
  timingFunction: 'ease-in-out',
};
